# Generated by Django 4.0.3 on 2022-04-05 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactform',
            old_name='name',
            new_name='lastname',
        ),
        migrations.AddField(
            model_name='contactform',
            name='firstname',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='contactform',
            name='subject',
            field=models.CharField(max_length=25, null=True),
        ),
    ]
