# Generated by Django 4.0.3 on 2022-04-06 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_rename_name_contactform_lastname_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContactForm',
        ),
    ]
