# Generated by Django 4.0.3 on 2022-04-06 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactform',
            old_name='lasttname',
            new_name='lastname',
        ),
    ]
