# Generated by Django 4.0.3 on 2022-04-06 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_rename_lasttname_contactform_lastname'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=20)),
                ('lastname', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=50)),
                ('tabletype', models.CharField(max_length=50)),
                ('guestnumber', models.CharField(max_length=70)),
                ('placements', models.CharField(max_length=40)),
                ('date', models.CharField(max_length=20)),
                ('time', models.CharField(max_length=20)),
                ('note', models.CharField(max_length=150)),
            ],
        ),
    ]
