# Generated by Django 4.0.3 on 2022-04-06 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_bookingtable'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookingtable',
            name='placements',
        ),
        migrations.AddField(
            model_name='bookingtable',
            name='placement',
            field=models.CharField(default=2, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bookingtable',
            name='tabletype',
            field=models.CharField(max_length=20),
        ),
    ]
