# Generated by Django 4.0.3 on 2022-04-11 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_remove_bookingtable_placements_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookMeal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('number', models.CharField(max_length=20)),
                ('itemname', models.CharField(max_length=50)),
                ('quantity', models.CharField(max_length=20)),
            ],
        ),
    ]
